package analiseLexico;

public enum Classification {
    $,                  //0
    ID,                 //1
    MENOR,              //2
    MAIOR,              //3
    MENORIGUAL,         //4
    MAIORIGUAL,         //5
    IGUAL,              //6
    DIFERENTE,          //7
    ADICAO,             //8
    SUBTRACAO,          //9
    MULTIPLICACAO,      //10
    DIVISAO,            //11
    ATRIBUICAO,         //12
    FECHAPARENTESES,    //13
    ABERTAPARENTESES,   //14
    FECHACHAVES,        //15
    ABERTACHAVES,       //16
    FECHACOLCHETES,     //17
    ABERTACOLCHETES,    //18
    VIRGULA,            //19
    PONTOVIRGULA,       //20
    PONTO,              //21
    MAIN,               //22
    IF,                 //23
    ELSE,               //24
    WHILE,              //25
    DO,                 //26
    FOR,                //27
    INT,                //28
    FLOAT,              //29
    CHAR,               //30
    LITERAL,            //31
    TIPOINT,            //32
    TIPOCHAR,           //33
    TIPOFLOAT,          //34
    PRINTF,             //35
}
